
**1.Merge**

In [1]:
import pandas as pd

In [3]:
data_root = 'C:/Users/c/Documents/dsga1001/1001-term-project/data/'

In [4]:
df=pd.read_csv(data_root+'02-build/clean/2019q3/2019q3merged.csv')

In [6]:
df.shape

(3655, 102)

In [7]:
df1=pd.read_csv(data_root+'02-build/clean/2019q3/sec_data_wide.csv')
df2=pd.read_csv(data_root+'01-raw/web_scraping/2019q3/merged/2019q3_web_scraping_merged.csv')

In [8]:
df1.shape

(3783, 98)

In [9]:
df1.head()

,Unnamed: 0,adsh,company_name,dyrqt,filed,cik,sic,ticker,country,period,...,ShareBasedCompensation,Short Term Investments,StockIssuedDuringPeriodValue,StockholdersEquity,SubleaseIncome,TotalLiabilities,TreasuryStockShares,TreasuryStockValue,WeightedAverageNumberOfDilutedSharesOutstanding,WeightedAverageNumberOfSharesOutstandingBasic
0,0,0000002178-19-000086,"ADAMS RESOURCES & ENERGY, INC.",201902,2019-08-07 00:00:00,2178,5172.0,ae,US,2019-06-30,...,74000.0,0.0,0.0,1.501080e+08,0.0,1.516560e+08,0.0,0.000000e+00,4.227000e+06,4.227000e+06
1,1,0000002488-19-000104,ADVANCED MICRO DEVICES INC,201902,2019-07-31 00:00:00,2488,3674.0,amd,US,2019-06-30,...,45000000.0,0.0,0.0,1.901000e+09,0.0,0.000000e+00,5000000.0,5.000000e+07,1.109000e+09,1.084000e+09
2,2,0000002969-19-000042,AIR PRODUCTS & CHEMICALS INC /DE/,201902,2019-07-25 00:00:00,2969,2810.0,apd,US,2019-06-30,...,9800000.0,0.0,0.0,1.172660e+10,0.0,7.805300e+09,29100445.0,2.033700e+09,2.219000e+08,2.206000e+08
3,3,0000003499-19-000017,ALEXANDERS INC,201902,2019-07-29 00:00:00,3499,6798.0,alx,US,2019-06-30,...,0.0,0.0,0.0,2.686100e+08,0.0,1.007861e+09,66160.0,3.680000e+05,5.118030e+06,0.000000e+00
4,4,0000003545-19-000100,ALICO INC,201902,2019-08-06 00:00:00,3545,100.0,alco,US,2019-06-30,...,0.0,0.0,0.0,1.832830e+08,0.0,2.162360e+08,946114.0,3.220500e+07,7.471000e+06,7.470000e+06

In [10]:
df1=df1.drop(['Unnamed: 0'], axis=1)

In [11]:
df2.shape

(3655, 6)

In [12]:
df2.head()

   Unnamed: 0 ticker   7_before    7_after  difference       per
0           0      a  69.712013  71.881348    2.169334  0.031119
1           0     aa  23.140000  20.914000   -2.226001 -0.096197
2           0    aac   0.575600   0.772400    0.196800  0.341904
3           0    aal  33.381995  30.765706   -2.616290 -0.078374
4           0   aamc   9.884000  11.036000    1.152000  0.116552

In [13]:
df2=df2.drop(['Unnamed: 0'], axis=1)

In [14]:
df= pd.merge(df1, df2)

In [15]:
df.shape

(3654, 101)

In [16]:
df.head()

,adsh,company_name,dyrqt,filed,cik,sic,ticker,country,period,AccountsPayableCurrent,...,SubleaseIncome,TotalLiabilities,TreasuryStockShares,TreasuryStockValue,WeightedAverageNumberOfDilutedSharesOutstanding,WeightedAverageNumberOfSharesOutstandingBasic,7_before,7_after,difference,per
0,0000002178-19-000086,"ADAMS RESOURCES & ENERGY, INC.",201902,2019-08-07 00:00:00,2178,5172.0,ae,US,2019-06-30,1.169830e+08,...,0.0,1.516560e+08,0.0,0.000000e+00,4.227000e+06,4.227000e+06,32.516730,32.435379,-0.081351,-0.002502
1,0000002488-19-000104,ADVANCED MICRO DEVICES INC,201902,2019-07-31 00:00:00,2488,3674.0,amd,US,2019-06-30,8.280000e+08,...,0.0,0.000000e+00,5000000.0,5.000000e+07,1.109000e+09,1.084000e+09,33.830000,29.320000,-4.509999,-0.133314
2,0000002969-19-000042,AIR PRODUCTS & CHEMICALS INC /DE/,201902,2019-07-25 00:00:00,2969,2810.0,apd,US,2019-06-30,1.543200e+09,...,0.0,7.805300e+09,29100445.0,2.033700e+09,2.219000e+08,2.206000e+08,224.774277,228.687637,3.913361,0.017410
3,0000003499-19-000017,ALEXANDERS INC,201902,2019-07-29 00:00:00,3499,6798.0,alx,US,2019-06-30,0.000000e+00,...,0.0,1.007861e+09,66160.0,3.680000e+05,5.118030e+06,0.000000e+00,364.644678,361.495618,-3.149060,-0.008636
4,0000003545-19-000100,ALICO INC,201902,2019-08-06 00:00:00,3545,100.0,alco,US,2019-06-30,4.318000e+06,...,0.0,2.162360e+08,946114.0,3.220500e+07,7.471000e+06,7.470000e+06,31.519748,30.789052,-0.730695,-0.023182

In [17]:
df.isnull().any()

adsh                                                                                                False
company_name                                                                                        False
dyrqt                                                                                               False
filed                                                                                               False
cik                                                                                                 False
sic                                                                                                 False
ticker                                                                                              False
country                                                                                             False
period                                                                                              False
AccountsPayableCurrent                                                                              False
AccountsReceivableNetCurrent                                                                        False
AccruedLiabilitiesCurrent                                                                           False
AccumulatedDepreciationDepletionAndAmortizationPropertyPlantAndEquipment                            False
AccumulatedOtherComprehensiveIncomeLoss                                                             False
AdditionalPaidInCapital                                                                             False
AdjustmentsToAdditionalPaidInCapitalSharebasedCompensationRequisiteServicePeriodRecognitionValue    False
AllowanceForDoubtfulAccountsReceivableCurrent                                                       False
AntidilutiveSecuritiesExcludedFromComputationOfEarningsPerShareAmount                               False
Assets                                                                                              False
AssetsCurrent                                                                                       False
CashAndCashEquivalents                                                                              False
CommonStockDividendsPerShareDeclared                                                                False
CommonStockParOrStatedValuePerShare                                                                 False
CommonStockSharesOutstanding                                                                        False
CommonStockValue                                                                                    False
ComprehensiveIncomeAttributableToNoncontrollingInterest                                             False
ComprehensiveIncomeNetOfTax                                                                         False
ContractWithCustomerLiability                                                                       False
ContractWithCustomerLiabilityCurrent                                                                False
ContractWithCustomerLiabilityNoncurrent                                                             False
                                                                                                    ...
OtherAssetsNoncurrent                                                                               False
OtherComprehensiveIncomeLoss                                                                        False
OtherLiabilitiesCurrent                                                                             False
OtherLiabilitiesNoncurrent                                                                          False
OtherNonoperatingIncomeExpense                                                                      False
PreferredStockParOrStatedValuePerShare                                                              False
PreferredStockSharesAuthorized                                                                      False
PreferredStockSharesIssued                                                                          False
PreferredStockSharesOutstanding                                                                     False
PrepaidExpenseCurrent                                                                               False
ProfessionalFees                                                                                    False
PropertyPlantAndEquipmentGross                                                                      False
PropertyPlantAndEquipmentNet                                                                        False
ResearchAndDevelopmentExpense                                                                       False
RetainedEarningsAccumulatedDeficit                                                                  False
Revenue                                                                                             False
ShareBasedCompensation                                                                              False
Short Term Investments                                                                              False
StockIssuedDuringPeriodValue                                                                        False
StockholdersEquity                                                                                  False
SubleaseIncome                                                                                      False
TotalLiabilities                                                                                    False
TreasuryStockShares                                                                                 False
TreasuryStockValue                                                                                  False
WeightedAverageNumberOfDilutedSharesOutstanding                                                     False
WeightedAverageNumberOfSharesOutstandingBasic                                                       False
7_before                                                                                            False
7_after                                                                                             False
difference                                                                                          False
per                                                                                                 False
Length: 101, dtype: bool

In [18]:
df=df.dropna(axis=0,how='any')
df.shape

(3654, 101)

In [24]:
df.head()

,adsh,company_name,dyrqt,filed,cik,sic,ticker,country,period,AccountsPayableCurrent,...,SubleaseIncome,TotalLiabilities,TreasuryStockShares,TreasuryStockValue,WeightedAverageNumberOfDilutedSharesOutstanding,WeightedAverageNumberOfSharesOutstandingBasic,7_before,7_after,difference,per
0,0000002178-19-000086,"ADAMS RESOURCES & ENERGY, INC.",201902,2019-08-07 00:00:00,2178,5172.0,ae,US,2019-06-30,1.169830e+08,...,0.0,1.516560e+08,0.0,0.000000e+00,4.227000e+06,4.227000e+06,32.516730,32.435379,-0.081351,-0.002502
1,0000002488-19-000104,ADVANCED MICRO DEVICES INC,201902,2019-07-31 00:00:00,2488,3674.0,amd,US,2019-06-30,8.280000e+08,...,0.0,0.000000e+00,5000000.0,5.000000e+07,1.109000e+09,1.084000e+09,33.830000,29.320000,-4.509999,-0.133314
2,0000002969-19-000042,AIR PRODUCTS & CHEMICALS INC /DE/,201902,2019-07-25 00:00:00,2969,2810.0,apd,US,2019-06-30,1.543200e+09,...,0.0,7.805300e+09,29100445.0,2.033700e+09,2.219000e+08,2.206000e+08,224.774277,228.687637,3.913361,0.017410
3,0000003499-19-000017,ALEXANDERS INC,201902,2019-07-29 00:00:00,3499,6798.0,alx,US,2019-06-30,0.000000e+00,...,0.0,1.007861e+09,66160.0,3.680000e+05,5.118030e+06,0.000000e+00,364.644678,361.495618,-3.149060,-0.008636
4,0000003545-19-000100,ALICO INC,201902,2019-08-06 00:00:00,3545,100.0,alco,US,2019-06-30,4.318000e+06,...,0.0,2.162360e+08,946114.0,3.220500e+07,7.471000e+06,7.470000e+06,31.519748,30.789052,-0.730695,-0.023182

**2.Save**

In [19]:
df.to_csv(data_root+'02-build/clean/2019q3/2019q3merged.csv', encoding='gbk')

In [25]:
test=pd.read_csv(data_root+'02-build/clean/2019q3/2019q3merged.csv')

In [26]:
test.shape

(3654, 102)

In [27]:
test.head()

,Unnamed: 0,adsh,company_name,dyrqt,filed,cik,sic,ticker,country,period,...,SubleaseIncome,TotalLiabilities,TreasuryStockShares,TreasuryStockValue,WeightedAverageNumberOfDilutedSharesOutstanding,WeightedAverageNumberOfSharesOutstandingBasic,7_before,7_after,difference,per
0,0,0000002178-19-000086,"ADAMS RESOURCES & ENERGY, INC.",201902,2019-08-07 00:00:00,2178,5172.0,ae,US,2019-06-30,...,0.0,1.516560e+08,0.0,0.000000e+00,4.227000e+06,4.227000e+06,32.516730,32.435379,-0.081351,-0.002502
1,1,0000002488-19-000104,ADVANCED MICRO DEVICES INC,201902,2019-07-31 00:00:00,2488,3674.0,amd,US,2019-06-30,...,0.0,0.000000e+00,5000000.0,5.000000e+07,1.109000e+09,1.084000e+09,33.830000,29.320000,-4.509999,-0.133314
2,2,0000002969-19-000042,AIR PRODUCTS & CHEMICALS INC /DE/,201902,2019-07-25 00:00:00,2969,2810.0,apd,US,2019-06-30,...,0.0,7.805300e+09,29100445.0,2.033700e+09,2.219000e+08,2.206000e+08,224.774277,228.687637,3.913361,0.017410
3,3,0000003499-19-000017,ALEXANDERS INC,201902,2019-07-29 00:00:00,3499,6798.0,alx,US,2019-06-30,...,0.0,1.007861e+09,66160.0,3.680000e+05,5.118030e+06,0.000000e+00,364.644678,361.495618,-3.149060,-0.008636
4,4,0000003545-19-000100,ALICO INC,201902,2019-08-06 00:00:00,3545,100.0,alco,US,2019-06-30,...,0.0,2.162360e+08,946114.0,3.220500e+07,7.471000e+06,7.470000e+06,31.519748,30.789052,-0.730695,-0.023182