In [14]:
import pandas as pd
import numpy as np
import os
import sys
nb_dir = os.path.split(os.getcwd())[0]
if nb_dir not in sys.path:
    sys.path.append(nb_dir)
from header import *

In [1]:
data_root = 'C:/Users/c/Documents/dsga1001/1001-term-project/data/'

In [2]:
from sklearn.linear_model import LinearRegression
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn import preprocessing

from sklearn.model_selection import train_test_split
from sklearn.model_selection import KFold

from sklearn.metrics import roc_curve, auc

import matplotlib.pyplot as plt

## Import

In [37]:
q3mergeddata = pd.read_csv(data_root + '02-build/clean/2019q3/2019q3merged.csv')

In [38]:
q3mergeddata.sic.value_counts()

2834.0    362
6022.0    178
6798.0    173
7372.0    116
2836.0     93
1311.0     91
3841.0     86
6021.0     73
7389.0     72
3674.0     70
6035.0     56
5812.0     43
6331.0     43
7374.0     42
6770.0     41
6282.0     35
3714.0     30
7370.0     28
3663.0     27
3845.0     27
7373.0     25
1389.0     25
4911.0     22
7011.0     22
6500.0     22
4813.0     20
8731.0     20
4922.0     20
3826.0     20
8071.0     20
         ...
3341.0      1
2024.0      1
2520.0      1
3716.0      1
2011.0      1
3715.0      1
6399.0      1
4950.0      1
6792.0      1
2761.0      1
6799.0      1
3080.0      1
8011.0      1
3910.0      1
4210.0      1
3330.0      1
3050.0      1
3652.0      1
3790.0      1
7330.0      1
3555.0      1
3211.0      1
3448.0      1
8111.0      1
2200.0      1
3579.0      1
3822.0      1
4013.0      1
3942.0      1
6159.0      1
Name: sic, Length: 382, dtype: int64

In [39]:
q3mergeddata['sic_new']=''
q3mergeddata.head()

,Unnamed: 0,adsh,company_name,dyrqt,filed,cik,sic,ticker,country,period,...,TotalLiabilities,TreasuryStockShares,TreasuryStockValue,WeightedAverageNumberOfDilutedSharesOutstanding,WeightedAverageNumberOfSharesOutstandingBasic,7_before,7_after,difference,per,sic_new
0,0,0000002178-19-000086,"ADAMS RESOURCES & ENERGY, INC.",201902,2019-08-07 00:00:00,2178,5172.0,ae,US,2019-06-30,...,1.516560e+08,0.0,0.000000e+00,4.227000e+06,4.227000e+06,32.516730,32.435379,-0.081351,-0.002502,
1,1,0000002488-19-000104,ADVANCED MICRO DEVICES INC,201902,2019-07-31 00:00:00,2488,3674.0,amd,US,2019-06-30,...,0.000000e+00,5000000.0,5.000000e+07,1.109000e+09,1.084000e+09,33.830000,29.320000,-4.509999,-0.133314,
2,2,0000002969-19-000042,AIR PRODUCTS & CHEMICALS INC /DE/,201902,2019-07-25 00:00:00,2969,2810.0,apd,US,2019-06-30,...,7.805300e+09,29100445.0,2.033700e+09,2.219000e+08,2.206000e+08,224.774277,228.687637,3.913361,0.017410,
3,3,0000003499-19-000017,ALEXANDERS INC,201902,2019-07-29 00:00:00,3499,6798.0,alx,US,2019-06-30,...,1.007861e+09,66160.0,3.680000e+05,5.118030e+06,0.000000e+00,364.644678,361.495618,-3.149060,-0.008636,
4,4,0000003545-19-000100,ALICO INC,201902,2019-08-06 00:00:00,3545,100.0,alco,US,2019-06-30,...,2.162360e+08,946114.0,3.220500e+07,7.471000e+06,7.470000e+06,31.519748,30.789052,-0.730695,-0.023182,

## Create dummy variable

In [40]:

for i in range(len(q3mergeddata)):
    if 0<q3mergeddata.sic[i]<=999:
        q3mergeddata.sic_new[i]='Agriculture, Forestry, And Fishing'
    if 1000<=q3mergeddata.sic[i]<=1499:
        q3mergeddata.sic_new[i]='Mining'
    if 1500<=q3mergeddata.sic[i]<=1799:
        q3mergeddata.sic_new[i]='Construction'
    if 2000<=q3mergeddata.sic[i]<=3999:
        q3mergeddata.sic_new[i]='Manufacturing'
    if 4000<=q3mergeddata.sic[i]<=4999:
        q3mergeddata.sic_new[i]='Transportation, Communications, Electric, Gas, And Sanitary Services'
    if 5000<=q3mergeddata.sic[i]<=5199:
        q3mergeddata.sic_new[i]='Wholesale Trade'
    if 5200<=q3mergeddata.sic[i]<=5999:
        q3mergeddata.sic_new[i]='Retail Trade'
    if 6000<=q3mergeddata.sic[i]<=6799:
        q3mergeddata.sic_new[i]='Finance, Insurance, And Real Estate'
    if 7000<=q3mergeddata.sic[i]<=8999:
        q3mergeddata.sic_new[i]='Services'
    if 9000<=q3mergeddata.sic[i]<=9999:
        q3mergeddata.sic_new[i]='Public Administration'

C:\Users\c\Anaconda3\lib\site-packages\ipykernel_launcher.py:14: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

C:\Users\c\Anaconda3\lib\site-packages\ipykernel_launcher.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  # Remove the CWD from sys.path while we load stuff.
C:\Users\c\Anaconda3\lib\site-packages\ipykernel_launcher.py:18: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
C:\Users\c\Anaconda3\lib\site-packages\ipykernel_launcher.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  after removing the cwd from sys.path.
C:\Users\c\Anaconda3\lib\site-packages\ipykernel_launcher.py:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  if sys.path[0] == '':
C:\Users\c\Anaconda3\lib\site-packages\ipykernel_launcher.py:20: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
C:\Users\c\Anaconda3\lib\site-packages\ipykernel_launcher.py:16: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  app.launch_new_instance()
C:\Users\c\Anaconda3\lib\site-packages\ipykernel_launcher.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

C:\Users\c\Anaconda3\lib\site-packages\ipykernel_launcher.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

In [42]:
q3_dummy=pd.get_dummies(q3mergeddata['sic_new'])

In [44]:
q3=pd.concat([q3mergeddata,q3_dummy],axis=1)

In [45]:
q3.head()

,Unnamed: 0,adsh,company_name,dyrqt,filed,cik,sic,ticker,country,period,...,sic_new,"Agriculture, Forestry, And Fishing",Construction,"Finance, Insurance, And Real Estate",Manufacturing,Mining,Retail Trade,Services,"Transportation, Communications, Electric, Gas, And Sanitary Services",Wholesale Trade
0,0,0000002178-19-000086,"ADAMS RESOURCES & ENERGY, INC.",201902,2019-08-07 00:00:00,2178,5172.0,ae,US,2019-06-30,...,Wholesale Trade,0,0,0,0,0,0,0,0,1
1,1,0000002488-19-000104,ADVANCED MICRO DEVICES INC,201902,2019-07-31 00:00:00,2488,3674.0,amd,US,2019-06-30,...,Manufacturing,0,0,0,1,0,0,0,0,0
2,2,0000002969-19-000042,AIR PRODUCTS & CHEMICALS INC /DE/,201902,2019-07-25 00:00:00,2969,2810.0,apd,US,2019-06-30,...,Manufacturing,0,0,0,1,0,0,0,0,0
3,3,0000003499-19-000017,ALEXANDERS INC,201902,2019-07-29 00:00:00,3499,6798.0,alx,US,2019-06-30,...,"Finance, Insurance, And Real Estate",0,0,1,0,0,0,0,0,0
4,4,0000003545-19-000100,ALICO INC,201902,2019-08-06 00:00:00,3545,100.0,alco,US,2019-06-30,...,"Agriculture, Forestry, And Fishing",1,0,0,0,0,0,0,0,0

In [46]:
df.isnull().any()

Unnamed: 0                                                                                          False
adsh                                                                                                False
company_name                                                                                        False
dyrqt                                                                                               False
filed                                                                                               False
cik                                                                                                 False
sic                                                                                                 False
ticker                                                                                              False
country                                                                                             False
period                                                                                              False
AccountsPayableCurrent                                                                              False
AccountsReceivableNetCurrent                                                                        False
AccruedLiabilitiesCurrent                                                                           False
AccumulatedDepreciationDepletionAndAmortizationPropertyPlantAndEquipment                            False
AccumulatedOtherComprehensiveIncomeLoss                                                             False
AdditionalPaidInCapital                                                                             False
AdjustmentsToAdditionalPaidInCapitalSharebasedCompensationRequisiteServicePeriodRecognitionValue    False
AllowanceForDoubtfulAccountsReceivableCurrent                                                       False
AntidilutiveSecuritiesExcludedFromComputationOfEarningsPerShareAmount                               False
Assets                                                                                              False
AssetsCurrent                                                                                       False
CashAndCashEquivalents                                                                              False
CommonStockDividendsPerShareDeclared                                                                False
CommonStockParOrStatedValuePerShare                                                                 False
CommonStockSharesOutstanding                                                                        False
CommonStockValue                                                                                    False
ComprehensiveIncomeAttributableToNoncontrollingInterest                                             False
ComprehensiveIncomeNetOfTax                                                                         False
ContractWithCustomerLiability                                                                       False
ContractWithCustomerLiabilityCurrent                                                                False
                                                                                                    ...
ProfessionalFees                                                                                    False
PropertyPlantAndEquipmentGross                                                                      False
PropertyPlantAndEquipmentNet                                                                        False
ResearchAndDevelopmentExpense                                                                       False
RetainedEarningsAccumulatedDeficit                                                                  False
Revenue                                                                                             False
ShareBasedCompensation                                                                              False
Short Term Investments                                                                              False
StockIssuedDuringPeriodValue                                                                        False
StockholdersEquity                                                                                  False
SubleaseIncome                                                                                      False
TotalLiabilities                                                                                    False
TreasuryStockShares                                                                                 False
TreasuryStockValue                                                                                  False
WeightedAverageNumberOfDilutedSharesOutstanding                                                     False
WeightedAverageNumberOfSharesOutstandingBasic                                                       False
7_before                                                                                            False
7_after                                                                                             False
difference                                                                                          False
per                                                                                                 False
sic_new                                                                                             False
Agriculture, Forestry, And Fishing                                                                  False
Construction                                                                                        False
Finance, Insurance, And Real Estate                                                                 False
Manufacturing                                                                                       False
Mining                                                                                              False
Retail Trade                                                                                        False
Services                                                                                            False
Transportation, Communications, Electric, Gas, And Sanitary Services                                False
Wholesale Trade                                                                                     False
Length: 112, dtype: bool

## Adjust columns

In [55]:
q3=q3.drop(['sic_new'],axis=1)

In [ ]:
cols = q3.columns.tolist()

In [63]:
cols=cols[:-13]+cols[-9:]+cols[-13:-9]

In [65]:
q3=q3[cols]

## Save

In [66]:
q3.to_csv(data_root+'02-build/clean/2019q3/2019q3_dummy.csv', encoding='gbk')

In [67]:
test=pd.read_csv(data_root+'02-build/clean/2019q3/2019q3_dummy.csv')
test.head()

,Unnamed: 0,Unnamed: 0.1,adsh,company_name,dyrqt,filed,cik,sic,ticker,country,...,Manufacturing,Mining,Retail Trade,Services,"Transportation, Communications, Electric, Gas, And Sanitary Services",Wholesale Trade,7_before,7_after,difference,per
0,0,0,0000002178-19-000086,"ADAMS RESOURCES & ENERGY, INC.",201902,2019-08-07 00:00:00,2178,5172.0,ae,US,...,0,0,0,0,0,1,32.516730,32.435379,-0.081351,-0.002502
1,1,1,0000002488-19-000104,ADVANCED MICRO DEVICES INC,201902,2019-07-31 00:00:00,2488,3674.0,amd,US,...,1,0,0,0,0,0,33.830000,29.320000,-4.509999,-0.133314
2,2,2,0000002969-19-000042,AIR PRODUCTS & CHEMICALS INC /DE/,201902,2019-07-25 00:00:00,2969,2810.0,apd,US,...,1,0,0,0,0,0,224.774277,228.687637,3.913361,0.017410
3,3,3,0000003499-19-000017,ALEXANDERS INC,201902,2019-07-29 00:00:00,3499,6798.0,alx,US,...,0,0,0,0,0,0,364.644678,361.495618,-3.149060,-0.008636
4,4,4,0000003545-19-000100,ALICO INC,201902,2019-08-06 00:00:00,3545,100.0,alco,US,...,0,0,0,0,0,0,31.519748,30.789052,-0.730695,-0.023182